DROP SEQUENCE IF EXISTS id_seq_pilot;
DROP SEQUENCE IF EXISTS id_seq_tech;
DROP SEQUENCE IF EXISTS id_seq_plane;
DROP SEQUENCE IF EXISTS id_seq_flight;
DROP SEQUENCE IF EXISTS id_seq_reservation;
DROP SEQUENCE IF EXISTS id_seq_finfo;

CREATE SEQUENCE id_seq_pilot START WITH 250;
CREATE SEQUENCE id_seq_tech START WITH 250;
CREATE SEQUENCE id_seq_plane START WITH 1100;
CREATE SEQUENCE id_seq_flight START WITH 1999;
CREATE SEQUENCE id_seq_reservation START WITH 9999;
CREATE SEQUENCE id_seq_finfo START WITH 1999;

