CREATE SEQUENCE id_seq_pilot START WITH 50;
CREATE SEQUENCE id_seq_tech START WITH 10;
CREATE SEQUENCE id_seq_plane START WITH 100;
CREATE SEQUENCE id_seq_flight START WITH 1000;
CREATE SEQUENCE id_seq_reservation START WITH 9999;
